import type { Vehicle, Review, Booking } from "./types";

const img = (seed: string) =>
  `https://images.unsplash.com/${seed}?w=1200&q=80&auto=format&fit=crop`;

export const vehicles: Vehicle[] = [
  {
    id: "v1",
    name: "Tesla Model S Plaid",
    brand: "Tesla",
    model: "Model S",
    year: 2024,
    type: "electric",
    fuel: "electric",
    transmission: "automatic",
    seats: 5,
    pricePerDay: 189,
    rating: 4.9,
    reviewCount: 128,
    location: "San Francisco, CA",
    image: img("photo-1617788138017-80ad40651399"),
    images: [
      img("photo-1617788138017-80ad40651399"),
      img("photo-1560958089-b8a1929cea89"),
      img("photo-1554744512-d6c603f27c54"),
    ],
    features: ["Autopilot", "Premium Audio", "Glass Roof", "Heated Seats", "Supercharging"],
    available: true,
    description: "The fastest production car ever made. Experience uncompromising performance with zero emissions.",
    specs: { mileage: "405 mi range", engine: "Tri-Motor Electric", topSpeed: "200 mph", acceleration: "1.99s 0-60" },
  },
  {
    id: "v2",
    name: "BMW M4 Competition",
    brand: "BMW",
    model: "M4",
    year: 2024,
    type: "luxury",
    fuel: "petrol",
    transmission: "automatic",
    seats: 4,
    pricePerDay: 245,
    rating: 4.8,
    reviewCount: 94,
    location: "Los Angeles, CA",
    image: img("photo-1555215695-3004980ad54e"),
    images: [img("photo-1555215695-3004980ad54e"), img("photo-1503376780353-7e6692767b70")],
    features: ["M Sport Package", "Carbon Fiber", "Harman Kardon", "Sport Exhaust"],
    available: true,
    description: "Track-bred performance with everyday usability. Pure driving pleasure.",
    specs: { mileage: "22 mpg", engine: "3.0L Twin-Turbo I6", topSpeed: "180 mph", acceleration: "3.8s 0-60" },
  },
  {
    id: "v3",
    name: "Range Rover Sport",
    brand: "Land Rover",
    model: "Range Rover Sport",
    year: 2024,
    type: "suv",
    fuel: "hybrid",
    transmission: "automatic",
    seats: 7,
    pricePerDay: 220,
    rating: 4.7,
    reviewCount: 76,
    location: "Miami, FL",
    image: img("photo-1606664515524-ed2f786a0bd6"),
    images: [img("photo-1606664515524-ed2f786a0bd6")],
    features: ["Air Suspension", "Meridian Audio", "Panoramic Roof", "AWD", "Towing Pkg"],
    available: true,
    description: "Luxury meets capability. Conquer any terrain in absolute comfort.",
    specs: { mileage: "26 mpg", engine: "3.0L Hybrid I6", topSpeed: "155 mph", acceleration: "5.2s 0-60" },
  },
  {
    id: "v4",
    name: "Porsche 911 Carrera",
    brand: "Porsche",
    model: "911",
    year: 2024,
    type: "convertible",
    fuel: "petrol",
    transmission: "automatic",
    seats: 4,
    pricePerDay: 320,
    rating: 5.0,
    reviewCount: 152,
    location: "Las Vegas, NV",
    image: img("photo-1503376780353-7e6692767b70"),
    images: [img("photo-1503376780353-7e6692767b70")],
    features: ["Sport Chrono", "PASM", "Bose Audio", "Sport Exhaust", "PDK"],
    available: true,
    description: "The benchmark of sports cars. Timeless design, modern performance.",
    specs: { mileage: "20 mpg", engine: "3.0L Twin-Turbo Flat-6", topSpeed: "182 mph", acceleration: "4.0s 0-60" },
  },
  {
    id: "v5",
    name: "Toyota Camry Hybrid",
    brand: "Toyota",
    model: "Camry",
    year: 2024,
    type: "sedan",
    fuel: "hybrid",
    transmission: "automatic",
    seats: 5,
    pricePerDay: 65,
    rating: 4.6,
    reviewCount: 312,
    location: "New York, NY",
    image: img("photo-1621007947382-bb3c3994e3fb"),
    images: [img("photo-1621007947382-bb3c3994e3fb")],
    features: ["Apple CarPlay", "Safety Sense 2.5", "Heated Seats", "Backup Camera"],
    available: true,
    description: "Reliable, efficient, and comfortable. The perfect everyday companion.",
    specs: { mileage: "52 mpg", engine: "2.5L Hybrid I4", topSpeed: "135 mph", acceleration: "7.6s 0-60" },
  },
  {
    id: "v6",
    name: "Mercedes-Benz V-Class",
    brand: "Mercedes",
    model: "V-Class",
    year: 2024,
    type: "van",
    fuel: "diesel",
    transmission: "automatic",
    seats: 8,
    pricePerDay: 145,
    rating: 4.7,
    reviewCount: 58,
    location: "Chicago, IL",
    image: img("photo-1609521263047-f8f205293f24"),
    images: [img("photo-1609521263047-f8f205293f24")],
    features: ["Captain Chairs", "Burmester Audio", "Ambient Lighting", "Dual Sunroof"],
    available: false,
    description: "Luxury travel for the whole family. Space and sophistication redefined.",
    specs: { mileage: "28 mpg", engine: "2.0L Diesel I4", topSpeed: "130 mph", acceleration: "9.1s 0-60" },
  },
  {
    id: "v7",
    name: "Audi e-tron GT",
    brand: "Audi",
    model: "e-tron GT",
    year: 2024,
    type: "electric",
    fuel: "electric",
    transmission: "automatic",
    seats: 5,
    pricePerDay: 215,
    rating: 4.9,
    reviewCount: 87,
    location: "Seattle, WA",
    image: img("photo-1614200187524-dc4b892acf16"),
    images: [img("photo-1614200187524-dc4b892acf16")],
    features: ["Matrix LED", "Bang & Olufsen", "Adaptive Air Suspension", "Sport Diff"],
    available: true,
    description: "Electric grand touring at its finest. Style and silence unite.",
    specs: { mileage: "238 mi range", engine: "Dual Motor Electric", topSpeed: "152 mph", acceleration: "3.1s 0-60" },
  },
  {
    id: "v8",
    name: "Ford Mustang GT",
    brand: "Ford",
    model: "Mustang",
    year: 2024,
    type: "convertible",
    fuel: "petrol",
    transmission: "manual",
    seats: 4,
    pricePerDay: 135,
    rating: 4.7,
    reviewCount: 201,
    location: "Austin, TX",
    image: img("photo-1547245324-d777c6f05e80"),
    images: [img("photo-1547245324-d777c6f05e80")],
    features: ["V8 Power", "Brembo Brakes", "Track Apps", "Active Exhaust"],
    available: true,
    description: "American muscle, refined. The legend continues with raw power.",
    specs: { mileage: "19 mpg", engine: "5.0L V8", topSpeed: "163 mph", acceleration: "4.2s 0-60" },
  },
];

export const reviews: Review[] = [
  { id: "r1", user: "Sarah Chen", avatar: "SC", rating: 5, date: "2 weeks ago", comment: "Absolutely flawless experience. The car was pristine and pickup was seamless." },
  { id: "r2", user: "Marcus Johnson", avatar: "MJ", rating: 5, date: "1 month ago", comment: "Best rental I've ever had. The team went above and beyond." },
  { id: "r3", user: "Elena Rossi", avatar: "ER", rating: 4, date: "1 month ago", comment: "Great vehicle, smooth process. Will rent again." },
  { id: "r4", user: "David Kim", avatar: "DK", rating: 5, date: "2 months ago", comment: "Premium service from start to finish. Highly recommended." },
];

export const bookings: Booking[] = [
  {
    id: "b1",
    userId: "u1",
    vehicleId: "v1",
    vehicleName: "Tesla Model S Plaid",
    vehicleImage: vehicles[0].image,
    startDate: "2026-06-15",
    endDate: "2026-06-20",
    pickupLocation: "San Francisco Airport",
    dropoffLocation: "San Francisco Airport",
    totalPrice: 945,
    status: "confirmed",
    createdAt: "2026-05-20",
    customerName: "Sarah Chen",
    customerEmail: "sarah@example.com",
    customerPhone: "+1 (555) 123-4567",
    rentalDays: 5,
    subtotal: 945,
    serviceFee: 113,
    taxAmount: 90,
    depositAmount: 500,
  },
  {
    id: "b2",
    userId: "u1",
    vehicleId: "v4",
    vehicleName: "Porsche 911 Carrera",
    vehicleImage: vehicles[3].image,
    startDate: "2026-05-10",
    endDate: "2026-05-13",
    pickupLocation: "Las Vegas Strip",
    dropoffLocation: "Las Vegas Strip",
    totalPrice: 960,
    status: "completed",
    createdAt: "2026-04-28",
    customerName: "Sarah Chen",
    customerEmail: "sarah@example.com",
    customerPhone: "+1 (555) 123-4567",
    rentalDays: 3,
    subtotal: 960,
    serviceFee: 115,
    taxAmount: 91,
    depositAmount: 500,
  },
  {
    id: "b3",
    userId: "u1",
    vehicleId: "v3",
    vehicleName: "Range Rover Sport",
    vehicleImage: vehicles[2].image,
    startDate: "2026-07-01",
    endDate: "2026-07-07",
    pickupLocation: "Miami Downtown",
    dropoffLocation: "Miami Beach",
    totalPrice: 1540,
    status: "pending",
    createdAt: "2026-05-25",
    customerName: "Sarah Chen",
    customerEmail: "sarah@example.com",
    customerPhone: "+1 (555) 123-4567",
    rentalDays: 6,
    subtotal: 1320,
    serviceFee: 158,
    taxAmount: 126,
    depositAmount: 500,
  },
];

export const testimonials = [
  { name: "Alexandra Pierce", role: "Travel Blogger", avatar: "AP", quote: "DriveLux redefined what I expect from a car rental. Premium fleet, zero hassle." },
  { name: "Jonathan Reyes", role: "Business Executive", avatar: "JR", quote: "I rent through DriveLux every week for client meetings. Always reliable, always premium." },
  { name: "Maya Patel", role: "Adventure Seeker", avatar: "MP", quote: "From city sedans to weekend convertibles — the variety and quality is unmatched." },
];

export const faqs = [
  { q: "What documents do I need to rent a vehicle?", a: "A valid driver's license, government-issued ID, and a credit card in your name. International renters need a passport and IDP." },
  { q: "Is insurance included in the rental price?", a: "Basic liability coverage is included. Comprehensive and collision protection are available as add-ons during booking." },
  { q: "Can I cancel or modify my booking?", a: "Yes. Free cancellation up to 48 hours before pickup. Modifications can be made anytime through your dashboard." },
  { q: "Do you offer one-way rentals?", a: "Yes, between most major cities. A one-way fee may apply depending on the route and vehicle." },
  { q: "What is your fuel policy?", a: "Return the vehicle with the same fuel level as pickup. EVs should be returned charged to at least 70%." },
  { q: "Is there a minimum age to rent?", a: "Drivers must be at least 21. Premium and luxury vehicles require drivers 25 or older." },
];
